#include <hedley/hedley.h>

#if defined( BOOSTNNG_IS_SHARED ) && defined( BOOSTNNG_COMPILING )

#define BOOSTNNG_API_FUNCTIONS HEDLEY_PUBLIC
#define BOOSTNNG_API_CLASSES HEDLEY_PUBLIC

#elif defined( BOOSTNNG_IS_SHARED )

#define BOOSTNNG_API_FUNCTIONS HEDLEY_IMPORT
#define BOOSTNNG_API_CLASSES

#else

#define BOOSTNNG_API_FUNCTIONS
#define BOOSTNNG_API_CLASSES

#endif
