#include <hedley/hedley.h>

#if defined( BOOSTNNG_IS_SHARED ) && defined( BOOSTNNG_COMPILING )

#define BOOSTNNG_API_FUNCTIONS HEDLEY_PUBLIC
#define BOOSTNNG_API_CLASSES HEDLEY_PUBLIC

#elif defined( BOOSTNNG_IS_SHARED )

#define BOOSTNNG_API_FUNCTIONS HEDLEY_IMPORT

#if defined( _WIN32 ) || defined( __CYGWIN__ )
#define BOOSTNNG_API_CLASSES HEDLEY_IMPORT
#else
#define BOOSTNNG_API_CLASSES
#endif

#else

#define BOOSTNNG_API_FUNCTIONS
#define BOOSTNNG_API_CLASSES

#endif
